title: Xianquan (Sarinstein) Yan's Homepage
description: Xianquan (Sarinstein) Yan's Homepage
theme: just-the-docs

url: https://sarinstein-yan.github.io

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
